# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date_added',
        ),
    ]
