# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_category_date_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_uploaded',
        ),
    ]
