# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0006_remove_category_date_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_category',
        ),
        migrations.AddField(
            model_name='image',
            name='image_category',
            field=models.ManyToManyField(to='pics.Category'),
        ),
    ]
