# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0008_auto_20180504_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
