# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0009_image_time_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.CharField(max_length=500),
        ),
    ]
